version: "2.8"

services:
  database_wevo:
    image: postgres
    container_name: database_wevo
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=database_wevo
    volumes:
      - pgdata:/data/postgres 
   
  app:
    build: .
    container_name: wevo_app
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database_wevo
    depends_on:
      - database_wevo
    
volumes:
  pgdata:
    driver: local